FEAT: socketIdMap에 존재하는 회원인지 검증하는 authGuard 개발 #43
gachimind/backend pull request #114
Opened 2023-01-24 10:38 UTC by bsh714-dev

On branch feat/43
 Changes to be committed:
	new file:   dist/src/logger.service.d.ts
	new file:   dist/src/logger.service.js
	new file:   dist/src/logger.service.js.map
	new file:   dist/src/middlewares/auth-guard.middleware.d.ts
	new file:   dist/src/middlewares/auth-guard.middleware.js
	new file:   dist/src/middlewares/auth-guard.middleware.js.map
	modified:   dist/src/middlewares/logger.middleware.d.ts
	modified:   dist/src/middlewares/logger.middleware.js
	modified:   dist/src/middlewares/logger.middleware.js.map
	modified:   dist/tsconfig.build.tsbuildinfo
	modified:   package-lock.json
	modified:   package.json
	new file:   src/logger.service.ts
	new file:   src/middlewares/auth-guard.middleware.ts
	modified:   src/middlewares/logger.middleware.ts

---
name: Pull Request
about: PR을 위해 작업한 상세 내용 작성
title: '[커밋 컨벤션 헤더] 제목'
labels: ''
assignees: ''

---

**작업한 내용**
가드 아직 구현하지 못함
윈스턴 로거 파일로 저장중

**REVIEW POINT**
노션이나 슬랙에 알람 설정 구현예정

2023-01-24 19:23 UTC, jn33-dev reviewed
세현님, 작업 완료되면 합치도록 해요!
우선 그냥 PR 열어두고, authguard 끝날때까지 계속 작업 붙여주시면 될것 같습니다.

2023-01-25 01:25 UTC, dy-p-code approved these changes

2023-01-27 19:03 UTC, jn33-dev requested changes
main.ts와 app.module.ts에 윈스턴 로거 의존성 주입이 안되어 있습니다.
아래 블로그 참고하셔서 주입해주세요.
[윈스턴 로거 의존성 주입 참고 블로그](https://velog.io/@aryang/NestJS-winston%EC%9C%BC%EB%A1%9C-%EB%A1%9C%EA%B7%B8-%EA%B4%80%EB%A6%AC)

그리고 최신 dev 브랜치를 pull 받으셔서 머지 후 push 해주세요.
dev 브랜치와 feat/43 브랜치 커밋이 많이 차이가 나서 package.json과 package-lock.json쪽에 컨플릭트가 납니다. 
세현님이 로컬 feat/43 브랜치에 최신 dev 버전을 pull 받으셔야 그나마 덜 날것 같습니다.

2023-01-27 19:03 UTC, jn33-dev commented on project/src/middlewares/logger.middleware.ts
>      }
기존에 콘솔에 텍스트 로깅 하던 내장 로거 내용이 완전히 삭제가 되었네요..

코드를 보니까, console에 로깅하는 기능이 없어 보이는데 맞나요?? 확인 부탁드립니다.

2023-01-28 14:00 UTC, closed without merging