네이버 지식백과 크롤링 API
gachimind/backend pull request #120
Opened 2023-01-25 13:46 UTC by dy-p-code

---
name: Pull Request
about: 네이버 지식백과 크롤링 API
title: 네이버 지식백과 크롤링 API
labels: backend, enhancement
assignees: 편도영

---

**작업한 내용**
네이버 지식백과 크롤링 API 구현
단어만 긁어오고 힌트 부분은 쿼리가 달라서 아직 처리 못

**REVIEW POINT**
데이터 1000개까지만 저장 가능 (RDS 프리티어의 한계로 예상)

2023-01-25 13:50 UTC, bsh714-dev approved these changes

2023-01-25 15:21 UTC, bsh714-dev approved these changes

2023-01-25 17:55 UTC, jn33-dev requested changes
도영님, 추가 요청사항 코멘트로 남겼습니다.
반영 부탁드려요.
그리고 redis로 옮기는 작업은 다른 이슈로 작업하시나요??

2023-01-25 17:55 UTC, jn33-dev commented on project/src/keyword/keyword.module.ts
> +    providers: [KeywordService],
exports: [TypeOrmModule] 추가해주세요~

그래야 다른 모듈에서 해당 엔티티를 사용할 수 있습니다!

2023-01-25 17:55 UTC, jn33-dev commented on project/src/app.module.ts
> +            entities: [User, TokenMap, Room, Player, SocketIdMap, Keyword],
여기에 하신 것 처럼, root 디랙토리에 있는 dataSource.ts 파일에도 추가해주세요!
임포트 하실때, 엔티티 임포트 경로는 상대경로로 해주셔야 에러가 안납니다!

2023-01-26 02:52 UTC, dy-p-code commented on project/src/keyword/keyword.module.ts
> +    providers: [KeywordService],
오잉 수정본이 안올라갔네요. 다시 수정해서 올렸습니다 :)

2023-01-26 02:53 UTC, dy-p-code commented on project/src/keyword/keyword.module.ts
> +    providers: [KeywordService],
redis 옮기는 작업은 다른 이슈로 할게요~

2023-01-26 03:20 UTC, dy-p-code commented on project/src/app.module.ts
> +            entities: [User, TokenMap, Room, Player, SocketIdMap, Keyword],
수정했씁니다!

2023-01-26 05:56 UTC, jn33-dev requested changes
도영님, 현재 dataSource.ts에 임포트 하신 경로가 상대경로입니다.
나머지는 상대경로로 있던 것을 다 절대경로로 변경하셨네요...;;;
다시 상대경로로 수정부탁드립니다.

그리고, dev 브랜치랑 충돌나는데, 수정하시면 제가 풀 받아서 컨플릭트 해결 할께요!

2023-01-26 06:13 UTC, dy-p-code commented
처음게 올라갔었네요ㅠ_ㅠ 다시 수정해서 올렸습니당

2023-01-26 06:19 UTC, jn33-dev approved these changes

2023-01-26 06:24 UTC, jn33-dev commented
컨플릭트 나는거 수정해서 올렸습니다~

2023-01-26 06:35 UTC, merged