FEAT : 유저 오늘 토탈 스코어 / 오늘 랭킹 / 게임 전체 스코어 API 구현
gachimind/backend pull request #154
Opened 2023-01-29 15:43 UTC by dy-p-code

---
name: Pull Request
about: FEAT : 유저 오늘 토탈 스코어 / 오늘 랭킹 / 게임 전체 스코어 API 구현
title:FEAT : 유저 오늘 토탈 스코어 / 오늘 랭킹 / 게임 전체 스코어 API 구현
labels: enhancement, backend
assignees: 편도영

---

**작업한 내용**
FEAT : 유저 오늘 토탈 스코어 / 오늘 랭킹 / 게임 전체 스코어 API 구현

**REVIEW POINT**
늦어져서 죄송합니다!

2023-01-30 00:42 UTC, jn33-dev requested changes
도영님, 커멘트 달았으니 확인하셔서 수정해주세요.
그리고, 컨트롤러 api UseGuards가 전부 주석처리 되어 있으니, 그 부분도 풀어서 푸쉬 해주세요!

고생 많으셨습니다!

2023-01-30 00:42 UTC, jn33-dev commented on project/src/users/users.service.ts
> +        });
JS에서 sort하지 마시고, db에서 가져올때, orderby 옵션을 사용해서 데이터 로드해주세요. 그럼 자동정렬된 배열로 들어옵니다.

2023-01-30 00:42 UTC, jn33-dev commented on project/src/users/users.service.ts
> +        });
turnResult를 사용하시면 데이터가 개수가 너무 많이 로드됩니다.
유저의 todayResult를 사용해서 합산하시면 그게 유저의 totalScore가 됩니다.
이 부분도 쿼리빌더를 사용해서 제가 이슈에 커멘트 달았던 코드 그대로 사용하시면, 유저의 토탈 점수를 db에서 자동으로 계산해서 가져오게 됩니다.

2023-01-30 00:42 UTC, jn33-dev commented on project/src/users/users.service.ts
> +        });
SUM 함수로 db에서 자동 계산된 점수를 받아오면 아래와 같이 배열을 새로 만들어서 push하고 reduce 할 필요가 없게 되어요

2023-01-30 00:58 UTC, bsh714-dev approved these changes

2023-01-30 13:05 UTC, jn33-dev requested changes
도영님, 간단한 수정사항 있습니다.
수정 마무리 부탁드립니다.

2023-01-30 13:05 UTC, jn33-dev commented on project/src/users/users.service.ts
> +        return sum;
도영님, sum 값 혹시 콘솔로 찍어 보셨나요??
db에서 처음 조회해 올 때, sum은 string으로 들어옵니다.
number 타입으로 변경 한 번 해주셔야 해요!

2023-01-31 14:49 UTC, jn33-dev requested changes
도영님, kakaoUserId 사용하는 모든 곳에서 변수면 변경해주세요!

2023-01-31 14:49 UTC, jn33-dev commented on project/src/users/users.service.ts
> +    async validateUser(userData: CreateUserDto): Promise<User> {
도영님, CreateUserDto에서 kakaoUserId를 OAuthUserId로 변경하고, 
kakao strategy 파일에서 kakaoUserId 변수명을 OAuthUserId로 변경해야 할 것 같습니다.
auth 폴더 내에 모든 곳에서 kakaoUserId로 되어 있는 것 다 바꿔주세요!

2023-01-31 14:57 UTC, jn33-dev requested changes
도영님 추가 요청드렸어요...

2023-01-31 14:57 UTC, jn33-dev commented on project/src/users/users.service.ts
> +        return convert;
도영님, 위에 `const { sum } = ...`은 객체 구조분해할당을 한거라서, 
실제 값은 `sum = '100'` 을 형태로 담겨 있습니다.
`{ sum }`은 `{sum : sum}`과 같습니다.

**`Number(sum)` 으로 다시 수정부탁드립니다.**
그리고  sum  값에 대해 다시 convert로 변수 할당할 필요 없으니, 바로 리턴해주세요.
`return Number(sum)`

2023-01-31 14:57 UTC, jn33-dev commented on project/src/users/users.service.ts
> +        return convert;
그리고.. 푸쉬 전에 작업하신 결과물 검증으로 console 한번만 찍어보시고 푸쉬 해주시면 감사하겠습니다...!

2023-01-31 16:09 UTC, jn33-dev requested changes
도영님, getUserDetailsByToken 함수의 return 값쪽 확인해서 수정해주세요!

2023-01-31 16:09 UTC, jn33-dev commented on project/src/users/users.service.ts
>          };
return 값에 todayRank, totalScore 0으로 고정되어 있는데, : 0 부분 삭제해주세요!

2023-02-01 03:36 UTC, jn33-dev approved these changes

2023-02-01 03:36 UTC, jn33-dev commented
고생 많으셨어요, 도영님!

2023-02-01 03:37 UTC, merged