FEAT : 닉네임 중복확인 API
gachimind/backend pull request #156
Opened 2023-01-30 08:33 UTC by dy-p-code

---
name: Pull Request
about: 닉네임 중복확인 API
title: 닉네임 중복확인 API
labels: backend, enhancement
assignees: 편도영

---

**작업한 내용**
닉네임 중복확인 API

**REVIEW POINT**
N/A

2023-01-30 12:54 UTC, jn33-dev requested changes
도영님, 수정 사항 있어 커멘트 남겼습니다.
여전히 수정해야 할 것들은 여러군데 보이지만, 그래도 처음보다는 일취월장 하신 듯 합니다!
그리고, 해당 PR에서 두 건의 이슈를 해결하고 계시니, PR 제목도 작업하신 내용이 잘 보이도록 수정 부탁드립니다!

close #151 #150

2023-01-30 12:54 UTC, jn33-dev commented on project/src/users/users.service.ts
> +        if (overlapCheck) {
위에서 **find** 함수로 찾으셨기 때문에, db에 동일 닉네임이 없더라도overlapCheck 변수에 []이 할당될겁니다.
if(overlapCheck) 조건 검사는 항상 true를 반환하게 된다는 얘기입니다.
console 찍어서 확인 한번 해주세요!

2023-01-30 12:54 UTC, jn33-dev commented on project/src/users/users.service.ts
> +        if (overlapCheck) {
그리고 애초에 db에서 nickname이 unique 값으로 설정 되어 있기 때문에, find를 할 필요 없이findOne으로 변경하시면, 지금 올려주신 조건문을 그대로 사용할 수 있습니다.

2023-01-30 12:54 UTC, jn33-dev commented on project/src/users/users.controller.ts
> +    @Get('/me/update')
@UseGuards(JwtAuthGuard) 붙여주세요

2023-01-30 12:54 UTC, jn33-dev commented on project/src/users/users.controller.ts
> +    async userInfoChange(@Headers() headers, @Body() Body) {
@Body() **Body** -> @Body() **body** 소문자로 바꿔주세요.

2023-01-30 12:54 UTC, jn33-dev commented on project/src/users/users.controller.ts
> +        await this.usersService.userInfoChange(token, Body);
여기서 Body가 {data: {nickname: stiring, profileImg: string}}으로 들어올텐데, 한 겹 까서 넣어야 되지 않을까요?
API 명세서 한번 확인해주세요~

2023-01-30 12:54 UTC, jn33-dev commented on project/src/users/users.service.ts
> +                const { nickname, profileImg } = Body;
controller 쪽에 Body 관련해서 커멘트 달아 두었습니다.
보시고 수정해주세요.

2023-01-31 03:42 UTC, bsh714-dev approved these changes

2023-01-31 15:04 UTC, jn33-dev requested changes
도영님, 수정해야 할 것 1, 확인해야 할 것 1 커멘트 달았습니다.

2023-01-31 15:04 UTC, jn33-dev commented on project/src/users/users.controller.ts
> +    async userInfoChange(@Headers() headers, @Body() Body) {
Body가 class가 아니라 변수명인데, 여전히 대문자로 받아오시면...
**`userInfoChange(@Headers() headers, @Body() body)`**
이렇게 변경 부탁드립니다.

2023-01-31 15:04 UTC, jn33-dev commented on project/src/users/users.controller.ts
> +        await this.usersService.userInfoChange(token, Body);
프런트에서 해당 요청에 대한 req.body 값이 {nickname, profileImg} 로 들어오는지, {data: {nickname: stiring, profileImg: string}}로 들어오는지 확인 하신건가요?
혜연님과 반듯이 확인 부탁드립니다.

2023-02-01 13:50 UTC, jn33-dev approved these changes
- 닉네임 검증 로직 추가
- updateUser dto 수정
- 에러핸들링 추가
- Get -> Post 메서드로 수정

결과물 잘 나오는 것 확인했습니다.

2023-02-01 13:50 UTC, jn33-dev commented on project/src/users/users.service.ts
> +                this.usersRepository.update({ nickname: nickname }, { profileImg: profileImg });
회원정보 수정이 됐다 안됐다 하는 이유는 두가지로 보입니다.
1. await이 빠져서 비동기 처리가 안됨
2. body 값으로 받는 nickname은 db에 없는 nickname이 들어오는 경우도 있는데, 지금 사용하신 update 방식이라면, nickname에 해당하는 모든 entity를 찾아 profileImg만 변경한다가 됩니다.
-> save 함수를 사용하시고, req.header에서 받은 token 값을 이용해 userId를 찾아서 진행해주세요.
save 함수로 db에 있는 데이터를 업데이트 하려면 반듯이 input 값에 PK 정보를 포함해야 됩니다.

2023-02-01 13:50 UTC, merged