FEAT: 버그제보 기록 API #11
gachimind/backend pull request #158
Opened 2023-01-31 12:25 UTC by bsh714-dev

---
name: Pull Request
about: PR을 위해 작업한 상세 내용 작성
title: '[커밋 컨벤션 헤더] 제목'
labels: ''
assignees: ''

---

**작업한 내용**
버그제보 기록 API

**REVIEW POINT**
_이번 PR에서 리뷰해야 할 포인트가 있다면 적어주세요._

2023-01-31 14:38 UTC, jn33-dev requested changes
세현님, logger.service 파일 middlewares 폴더로 이동해주세요.

2023-01-31 14:38 UTC, jn33-dev commented on project/src/middlewares/logger.middleware.ts
> +    constructor() {}
constructor는 사용 안해서 삭제하셔도 될 것 같습니다.

2023-01-31 14:38 UTC, jn33-dev commented on project/src/middlewares/logger.middleware.ts
> +        );
콘솔에 찍히는 모든 요청에 대한 로깅은 `${method} ${originalUrl} ${statusCode} ${contentLength} - ${userAgent} ${ip}` 이렇게 구성되도록 수정해주세요.
지금은 body, heade query 값이 모두 들어와 굉장히 읽기 힘든것 같아요ㅠ

2023-01-31 14:38 UTC, jn33-dev commented on project/src/logger.service.ts
> +                new winston.transports.Console({
말씀드린대로, 여기 블럭이 콘솔을 찍어주는 역할을 하는 블럭인지 체크해주세요.

2023-01-31 14:38 UTC, jn33-dev commented on project/src/logger.service.ts
> +                    level: 'debug',
레베 debug로 되어 있는데, 디버그 레벨 로깅이 어떤 걸 포함하고 있는지 확인 부탁드립니다.

2023-01-31 14:38 UTC, jn33-dev commented on project/src/logger.service.ts
> +    constructor(service: string) {
주입하신 service 체크 부탁드립니다.

2023-01-31 14:38 UTC, jn33-dev commented on project/src/logger.service.ts
> +                        nestWinstonModuleUtilities.format.nestLike(service, {
service 주입 수정 후에 콘솔에 찍히는 로깅 포맷이 잘 반영이 된다면, 윈스턴 로거만 두면 될 것 같습니다.

2023-01-31 14:38 UTC, jn33-dev commented on project/src/logger.service.ts
> +    }
이 레벨링 자동으로 되는지도 다시 한번 확인해주세요!

2023-02-01 17:16 UTC, jn33-dev requested changes
세현님, 원래 있던 내장 로거는 어차피 작동을 안해서 삭제하시면 됩니다. 
그런데, 지금 로거 폴더를 삭제하고 다시 돌려보시면 아마 폴더가 생성이 안되는 것 같습니다. 
이 부분 제 컴퓨터 문제인지 한번 확인해주세요.

2023-02-01 17:16 UTC, jn33-dev commented on project/src/admin/notion.service.ts
> +                일시: {
![image](https://user-images.githubusercontent.com/102890891/215790558-54faddd7-477b-49d9-b16c-5e5999c0ddcb.png)

이쪽에서 발생하는 에러 같은데, 이것도 확인 부탁드립니다!

2023-02-01 17:16 UTC, jn33-dev commented on project/src/admin/admin.controller.ts
> +    async bugReport(@Body() Body: BugDto) {
`@Body() Body` 여기에서 Body는 변수명을 지정하는 거라, body 소문자로 사용해주세요.

2023-02-01 17:16 UTC, jn33-dev commented on project/src/app.module.ts
> +            synchronize: false,
개발 단계에서 db 스키마 수정이 계속 발생하고 있습니다.
우선 개발 단계에서는 true로 놓고, 배포 후에 false로 변경하면 좋을 것 같습니다.

2023-02-01 17:16 UTC, jn33-dev commented on project/src/middlewares/logger.service.ts
> +const dailyOptions = (level: string) => {
parameter로 maxFiles: number도 같이 받도록 추가해주세요.

2023-02-01 17:16 UTC, jn33-dev commented on project/src/middlewares/logger.service.ts
> +        maxFiles: 30,
parameter 값으로 받은 maxFiles 옵션이 적용되도록 : 30 지워주세요

2023-02-01 17:16 UTC, jn33-dev commented on project/src/middlewares/logger.service.ts
> +            level: 'silly',
콘솔 옵션으로 아래와 같이 코드 수정해주세요.
```
level: process.env.NODE_ENV === 'production' ? 'http' : 'silly',
    format:
        process.env.NODE_ENV === 'production'
            ? combine(colorize({ all: true }), simple())
            : combine(
                  colorize({ all: true }),
                  timestamp({ format: 'YYYY-MM-DD HH:mm:ss:ms' }),
                  utilities.format.nestLike('가치마인드', {
                      prettyPrint: true,
                  }),
              ),
```

2023-02-01 17:16 UTC, jn33-dev commented on project/src/middlewares/logger.service.ts
> +    ],
파일 저장 함수는 아래와 같이 maxFiles 옵션과 함께 패싱해주세요.
```
        new winstonDaily(dailyOptions('info', 7)),
        new winstonDaily(dailyOptions('warn', 14)),
        new winstonDaily(dailyOptions('error', 30)),
```

2023-02-01 17:42 UTC, jn33-dev commented
세현님, 윈스턴 로거 옵션 수정해서 올렸습니다.

2023-02-01 17:43 UTC, jn33-dev approved these changes

2023-02-02 15:05 UTC, jn33-dev approved these changes
고생 많으셨습니다. 세현님! 머지 해주세요!

2023-02-02 15:05 UTC, jn33-dev commented on project/src/admin/admin.controller.ts
>          if (!Body) {
위에 변수 바뀌면 블럭 스콥 안에도 다 바꿔주셔야 해요 세현님ㅠㅠ

2023-02-02 15:10 UTC, dy-p-code approved these changes

2023-02-02 17:39 UTC, merged