FEAT : 카카오 로그인 Oauth 구현 및 회원정보조회 API 정리 완료
gachimind/backend pull request #38
Opened 2023-01-09 17:11 UTC by dy-p-code

---
name: Pull Request
about: 카카오로그인 oauth, 회원정보조회 API 작성 완료
title: FEAT : 카카오 로그인 Oauth 구현 및 회원정보조회 API 정리 완료
labels: backend, enhancement
assignees: 편도영

---

**작업한 내용**
- 카카오 로그인 Oauth 구현 및 회원정보조회 API 정리 완료했습니다.
- ERROR [ExceptionsHandler] Unknown authentication strategy "kakao" 에러가 뜨는데 이건 해결하지 못했습니다.

**REVIEW POINT**
- 폴더 구조 확인해주세요.
- oauth를 여러개 할거라면 auth, guards, serializer, strategy는 폴더를 별도로 놔두는게 좋을 것 같기도 합니다.

2023-01-10 09:54 UTC, jn33-dev requested changes
**1. users 도메인에서 수행해야 하는 기능을 두가지로 분리하면 좋을 것 같습니다.**
 - 회원 인증 (가입/로그인) 기능은 모두 auth.service에서 처리
 - 인증된 회원의 정보 조회 기능은 모두 users.service에서 처리


**2. 도메인별로 상위 폴더를 구성하고, 도메인 내에서 기능별로 폴더를 구성하면 될것 같습니다.**  
 - users/auth 폴더를 만들어 주세요. 
 - 해당 폴더에는 auth관련 유틸리티만 담도록 하면 좋겠습니다.
 - auth를 상위 폴더에서 생성하면, auth.module을 생성해야 하고, 어차피, users.controller에서 user authentication 관련 request를 모두 처리하고 있기때문에, users 폴더 내에 두는게 맞는 것 같습니다. 
 - auth.service는 users 폴더에 두고, 나머지는 아래를 참고해서 옮겨주세요.


**3. users/auth 폴더 내에는 아래의 파일들을 파일명을 변경해서 담아주세요.**
 - guard.service.ts -> kakao-auth.guard.ts
 - serializer.service.ts -> auth.serializer.ts
 - strategy.service.ts -> kakao-auth.strategy.ts

아래는 참고할만한 nestjs 레포지토리인데, 폴더 구조 한번 참고하시면 좋을 것 같습니다!
[zerocho 슬랙 클론코딩](https://github.com/ZeroCho/sleact/tree/master/nest-typeorm/src)
[restful best nestjs practice](https://github.com/chnirt/nestjs-restful-best-practice/tree/master/src/auth)

2023-01-10 09:54 UTC, jn33-dev commented on project/src/users/user.entity.ts
> +    createdAt: string;
이 부분은 mysql에서 자동 생성해주는 부분인데, type을 Date이 아니라 string으로 변경하신 이유가 궁금합니다.

2023-01-10 09:54 UTC, jn33-dev commented on project/src/types/express/index.d.ts
> +        }
여기 파일에서 정의한 Request interface는 모든 express request로 받는 user 변수에 자동으로 타입 검사를 해주는 설정인가요?? 어떻게 동작하는지 궁금합니다!

2023-01-10 09:54 UTC, jn33-dev commented on project/src/users/users.controller.ts
> +            return { msg: 'Not Authenticated' };
```
if (!request.user) throw new HttpException("에러 메세지", statuscode)
return {message: "Authenticated"}
```
형태로 변경해주시면 자동으로 requet.user 값이 없을 때, res.status().json({errorMessag: "에러메세지"}) 형태로 처리됩니다~

2023-01-10 09:54 UTC, jn33-dev commented on project/src/users/users.controller.ts
> +            return { msg: 'Not Authenticated' };
response 값은 프런트 담당인 혜연님과 얘기하셔서 api 명세서에 에러 케이스별로 메세지와 status 어떻게 전달할건지 정리해 주시면 감사하겠습니다.

2023-01-10 09:54 UTC, jn33-dev commented on project/src/users/users.service.ts
> +            throw new NotFoundException(`회원 인증에 실패했습니다.`);
모든 exception은 HttpException을 사용하시면 되고, notfound의 경우, status code 자리에 404를 적어주시면 됩니다.

2023-01-10 09:54 UTC, jn33-dev commented on project/src/users/users.service.ts
>      async findByUserId(userId: number): Promise<User> {
findByUserId는 auth.service에서 이미 구현을 하고 계시고, users.service에서는 findByUserId외에 정의된 메서드가 없어 보이는데, auth.service와 users.service를 분리해야 할 필요가 있을까요??

2023-01-10 09:54 UTC, jn33-dev commented on project/src/users/auth.service.ts
> +    async findUser(userId: number) {
메서드명을 findUserById로 변경하면 어떨까요?

그리고, 아래 users.service에서도 findUserById라는 메서드가 동일한 기능을 수행하고 있는데, 코드 재사용이 가능한지 한번 고민을 해보시면 좋을 것 같습니다.

2023-01-10 09:54 UTC, jn33-dev commented on project/src/users/users.controller.ts
> +        return this.usersService.findByUserId(userId);
(참고)유저 상세페이지에서 필요한 유저의 정보와 로그인했을 때 필요한 유저 정보를 분리해서 프런트로 보내주는 데이터를 구성하는 것이 좋을 것 같습니다.

그리고, 해당 메서드는 마이페이지에서 유저 상세 정보를 조회하는 것이니까, 메서드명도 getUserDetailsByUserId와 같이 어떤 기능을 수행하는건지 정확히 알 수 있도로고 변경해주시면 좋을 것 같습니다! (controller와 service 모두에서요!)
+ 전체적으로 메서드 이름만 보고 무슨 기능을 하는지 구별이 가능하도록 작명을 부탁드립니다~

2023-01-10 11:46 UTC, bsh714-dev approved these changes

2023-01-10 12:06 UTC, dy-p-code commented on project/src/users/user.entity.ts
> +    createdAt: string;
다른거 에러 처리하다가 잠시 바꿔둔거였는데 까먹고 date로 안돌려놨네요.  date로 다시 수정했습니다 :)

2023-01-10 12:18 UTC, dy-p-code commented on project/src/types/express/index.d.ts
> +        }
req에 임의 값을 넣어서 사용하는 방법입니다! users.controller.ts 파일에서 43번째 코드 줄 보면 request.user가 있어요. 여기서 user는 express가 기본으로 제공하는 타입을 쓰지 않고 제가 사용할 타입을 지정해서 사용할거라서 커스터마이징 해준거라고 생각하시면 될 것 같아요.

참고문서: https://www.typescriptlang.org/docs/handbook/tsconfig-json.html

2023-01-10 12:20 UTC, dy-p-code commented on project/src/users/users.controller.ts
> +            return { msg: 'Not Authenticated' };
수정했습니당 에러 문구랑 status는 이야기하고 다시 수정하겠습니다~

2023-01-10 12:21 UTC, dy-p-code commented on project/src/users/users.service.ts
> +            throw new NotFoundException(`회원 인증에 실패했습니다.`);
확인했습니다👍

2023-01-10 12:22 UTC, dy-p-code commented on project/src/users/users.service.ts
>      async findByUserId(userId: number): Promise<User> {
폴더 구조랑 JMT 토큰 때문에 일단 남겨둔거긴 한데, 일단 조금 고민 해보겠숩니다!

2023-01-10 12:24 UTC, dy-p-code commented on project/src/users/auth.service.ts
> +    async findUser(userId: number) {
넹~~ :)

2023-01-10 12:25 UTC, dy-p-code commented on project/src/users/users.controller.ts
> +        return this.usersService.findByUserId(userId);
넹 확인했숩니다 : )!!!

2023-01-11 02:07 UTC, jn33-dev approved these changes
지금 남아있는 커멘트 확인하셔서 resolve 해주시고, 머지 하시면 될것 같습니다!
그리고, jwt 발행하는 건은 별도의 issue로 처리하실 예정이신가요?

2023-01-11 02:07 UTC, jn33-dev commented on project/src/users/users.service.ts
> +            throw new NotFoundException('회원 인증에 실패했습니다.');
HttpException으로 던져 주셔야 {errorMessage: "에러메세지"} 형태로 나갑니다~

2023-01-11 02:07 UTC, jn33-dev commented on project/src/users/users.service.ts
>      async findByUserId(userId: number): Promise<User> {
제 생각에는 jwt도 결국 인증 과정 중에 하나로 보여서 auth.service에서 처리하는게 맞지 않나 싶습니다.
도영님께서 잘 판단하셔서 진행해주시면 될 것 같습니다!

2023-01-11 02:36 UTC, dy-p-code commented on project/src/users/users.service.ts
>      async findByUserId(userId: number): Promise<User> {
넹넹 :) !!

2023-01-11 02:37 UTC, dy-p-code commented on project/src/users/users.service.ts
> +            throw new NotFoundException('회원 인증에 실패했습니다.');
넹 수정했습니다~

2023-01-11 02:38 UTC, dy-p-code commented on project/src/users/users.service.ts
> +            throw new NotFoundException('회원 인증에 실패했습니다.');
jwt는 별도 issue 딱지 발행해서 진행하려고 합니다!

2023-01-11 02:50 UTC, merged