Feature/55
gachimind/backend pull request #59
Opened 2023-01-14 16:44 UTC by dy-p-code

**작업한 내용**
- 카카오 오어스 구현 완료, 프론트엔드와 확인 완료
- access token 발급하고 프론트엔드에 쿼리스트링 전달

**REVIEW POINT**
- 배포해서 확인 완료
- 새로 설치한 npm : @nestjs/jwt

2023-01-16 07:12 UTC, jn33-dev requested changes
고생 많으셨습니다!
훌륭하게 해내셨네요!!ㅎㅎ

tokenMap의 경우 엔티티 파일의 내용이 달라졌습니다.
feature/58 브랜치에서 변경 내용을 참고해주시고,
jwt 발행할때, tokenMap에 토큰값과 userId를 저장해주세요!

2023-01-16 07:12 UTC, jn33-dev commented on project/src/users/users.service.ts
>          return this.usersRepository.save(newUser);
create으로 새 유저의 엔티티 생성 후 save를 한번 더 하는 이유가 뭔지 궁금합니다!

2023-01-16 07:12 UTC, jn33-dev commented on project/src/users/users.service.ts
> +        return this.usersRepository.save(user);
db에 새로 유저 엔티티를 생성한다면, 굳이 쿼리를 두번 날리 필요가 없어 보입니다.
create이나 insert를 한번만 하면 되지 않을까요?

return 값에 userId를 포함해야 한다면, user와 details를 활용하여 객체를 만들어서 return하면 좋을 것 같습니다.

2023-01-16 07:12 UTC, jn33-dev commented on project/src/users/users.service.ts
> +        private readonly configService: ConfigService,
configService를 여기에 주입해야 하는 이유가 있을까요?

2023-01-16 07:12 UTC, jn33-dev commented on project/src/users/users.service.ts
> +        private readonly configService: ConfigService,
repository 외에는 굳이 주입해서 사용할 필요가 없어보입니다.

2023-01-16 07:12 UTC, jn33-dev commented on project/src/users/users.service.ts
>              throw new HttpException('회원 인증에 실패했습니다.', 402);
status 코드 401 아닌가 싶은데, 후론트 분들과 확인 한번 해주시면 좋을것 같습니다~

2023-01-16 08:25 UTC, bsh714-dev approved these changes

2023-01-17 01:35 UTC, jn33-dev reviewed
도영님!
엔티티 파일 지금 58번 브랜치에 있는 걸로 동기화 해주시고, User 테이블 말고 TokenMap 테이블에 토큰값과 유저 아이디를 저장해주세요.
안 그러면 게임 로직에서 코드를 다 바꿔야 합니다...ㅠㅠ

2023-01-17 23:52 UTC, closed without merging