헤더로 토큰을 받아와서 회원정보조회
gachimind/backend pull request #82
Opened 2023-01-19 15:44 UTC by dy-p-code

---
name: Pull Request
about: 헤더로 토큰을 받아와서 회원 정보 조회하기
title: 헤더로 토큰을 받아와서 회원정보조회
labels: enhancement, backend
assignees: 편도영

---

1. 헤더로 토큰 받아오기
2. 토큰을 bareer와 토큰값으로 분리하기
3. 토큰값으로 userinfo 찾기
4. userinfo로 user정보 조회해서 데이터 반환하기

**REVIEW POINT**
미완 / 토큰값이 들어오지 않아서 테스트 못함

2023-01-19 17:17 UTC, jn33-dev requested changes
도영님, 아프신대도 최선을 다 해주셔서 감사합니다!

몇가지 수정사항 있어서 코멘트 남겼으니, 확인해주세요!

2023-01-19 17:17 UTC, jn33-dev commented on project/src/users/users.controller.ts
> +        const token = headers.replace('Bearer ', '');
프런트에서 헤더로 쿠키 전달하지 않기 때문에, req.cookie로 접근 하시면 됩니다.
(서버에서도 쿠키 발행할때 헤더로 전달하지 않습니다.)

테스트 하실때는, 카카오 로그인 REDIRECT를 localhost:3000으로 두시고, 로그인 진행 후 api 호출하시면 쿠키가 잘 들어옵니다.

2023-01-19 17:17 UTC, jn33-dev commented on project/src/users/users.service.ts
> +            select: { userInfo: true },
userInfo로 하면 아마 userId만 나오지 싶습니다.
tokenMap에서 userInfo 컬럼 옵션에 eager: true로 설정이 되어 있습니다.
항상 user 정보를 다 가져오도록 하는 옵션입니다.
이미 디폴트로 정보를 불러오는 상황이라 select에서 userInfo:true 로 하면, 에러가 날 것 같아요..!

PR 하시기 전에 항상 테스트를 꼭 해보시고 PR 해주세요~

2023-01-19 17:17 UTC, jn33-dev commented on project/src/users/users.service.ts
> +        return userFindByToken;
유저 데이터를 불러오면 아래와 같이 정보를 가져오는데, 프런트에 정보를 return 할 때는, api 명세서에서 약속한 데이터 형태로 가공해서 return 하셔야 합니다!

![image](https://user-images.githubusercontent.com/102890891/213514325-9944d560-67db-4ac9-83fb-94a139bb7729.png)

2023-01-20 03:31 UTC, dy-p-code commented on project/src/users/users.controller.ts
> +        const token = headers.replace('Bearer ', '');
후론트(혜연님)와 다시 얘기해보니까 헤더로 전달해준다고 해서 헤더로 그대로 두었습니다 :)

2023-01-20 03:31 UTC, dy-p-code commented on project/src/users/users.service.ts
> +            select: { userInfo: true },
수정했습니다 :)

2023-01-20 03:31 UTC, dy-p-code commented on project/src/users/users.service.ts
> +        return userFindByToken;
넹! 이 부분도 수정했습니다!

2023-01-20 07:40 UTC, jn33-dev commented on project/src/users/users.controller.ts
> +        const tokenParsing = req.headers.authorization;
토큰 파싱을 jwt가드에서도 하고 있는데, 가드에서 파싱한 값을 컨트롤러로 넘길 수 있는 방법은 없을까요?

2023-01-20 10:37 UTC, bsh714-dev approved these changes

2023-01-20 12:38 UTC, closed without merging

2023-01-20 12:38 UTC, dy-p-code commented
82번 브랜치에 수정사항 올려서 그걸로 PR 날리겠습니다!